# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '(site|site/aws|site/raspberrypi|site/markdown|site/application|site/command\-line\-tool|site/en|site/search|site/database|site/programming\-language|site/assets|site/aws/aws_cli\-tips|site/aws/dynamodb|site/aws/dynamodb/dynamodb\-local|site/raspberrypi/raspberrypi\-ubuntu\-tips|site/markdown/markdown\-tips|site/application/shortcuts|site/application/vscode|site/application/obsidian|site/application/workflowy|site/application/inkscape|site/application/vscode/images|site/application/vscode/setting\-tips|site/application/vscode/extention\-tips|site/application/obsidian/community_plugins|site/application/obsidian/images|site/application/obsidian/community_plugins/auto_template_trigger|site/application/obsidian/community_plugins/plantuml|site/application/inkscape/images|site/command\-line\-tool/vi|site/command\-line\-tool/git|site/command\-line\-tool/vi/vi\-tips|site/command\-line\-tool/git/git\-tips|site/en/aws|site/en/raspberrypi|site/en/markdown|site/en/application|site/en/command\-line\-tool|site/en/database|site/en/programming\-language|site/en/aws/aws_cli\-tips|site/en/aws/dynamodb|site/en/aws/dynamodb/dynamodb\-local|site/en/raspberrypi/raspberrypi\-ubuntu\-tips|site/en/markdown/markdown\-tips|site/en/application/shortcuts|site/en/application/vscode|site/en/application/obsidian|site/en/application/workflowy|site/en/application/inkscape|site/en/application/vscode/images|site/en/application/vscode/setting\-tips|site/en/application/vscode/extention\-tips|site/en/application/obsidian/community_plugins|site/en/application/obsidian/images|site/en/application/obsidian/community_plugins/auto_template_trigger|site/en/application/obsidian/community_plugins/plantuml|site/en/application/inkscape/images|site/en/command\-line\-tool/vi|site/en/command\-line\-tool/git|site/en/command\-line\-tool/vi/vi\-tips|site/en/command\-line\-tool/git/git\-tips|site/en/database/mariadb|site/en/database/mongodb|site/en/database/dynamodb|site/en/database/mongodb/images|site/en/database/mongodb/pymongo|site/en/database/mongodb/mongosh|site/en/database/mongodb/install\-mongodb|site/en/database/mongodb/mongodb\-compass|site/en/programming\-language/applescript|site/en/programming\-language/python|site/en/programming\-language/applescript/example|site/en/programming\-language/python/images|site/en/programming\-language/python/pre\-commit\-tips|site/en/programming\-language/python/pymysql\-tips|site/en/programming\-language/python/mdformat\-tips|site/en/programming\-language/python/mkdocs|site/en/programming\-language/python/mkdocs\-tips|site/en/programming\-language/python/post\-commit\-tips|site/en/programming\-language/python/dash\-plotly\-tips|site/en/programming\-language/python/mkdocs/doc_config\-tips|site/en/programming\-language/python/mkdocs/display\-config_tips|site/database/mariadb|site/database/mongodb|site/database/dynamodb|site/database/mongodb/images|site/database/mongodb/pymongo|site/database/mongodb/mongosh|site/database/mongodb/install\-mongodb|site/database/mongodb/mongodb\-compass|site/programming\-language/applescript|site/programming\-language/python|site/programming\-language/applescript/example|site/programming\-language/python/images|site/programming\-language/python/pre\-commit\-tips|site/programming\-language/python/pymysql\-tips|site/programming\-language/python/mdformat\-tips|site/programming\-language/python/mkdocs|site/programming\-language/python/post\-commit\-tips|site/programming\-language/python/dash\-plotly\-tips|site/programming\-language/python/mkdocs/doc_config\-tips|site/programming\-language/python/mkdocs/display\-config_tips|site/assets/images|site/assets/img|site/assets/stylesheets|site/assets/javascripts|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min)/.*'
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
        # Unify line break code to LF
        exclude: '(site|site/aws|site/raspberrypi|site/markdown|site/application|site/command\-line\-tool|site/en|site/search|site/database|site/programming\-language|site/assets|site/aws/aws_cli\-tips|site/aws/dynamodb|site/aws/dynamodb/dynamodb\-local|site/raspberrypi/raspberrypi\-ubuntu\-tips|site/markdown/markdown\-tips|site/application/shortcuts|site/application/vscode|site/application/obsidian|site/application/workflowy|site/application/inkscape|site/application/vscode/images|site/application/vscode/setting\-tips|site/application/vscode/extention\-tips|site/application/obsidian/community_plugins|site/application/obsidian/images|site/application/obsidian/community_plugins/auto_template_trigger|site/application/obsidian/community_plugins/plantuml|site/application/inkscape/images|site/command\-line\-tool/vi|site/command\-line\-tool/git|site/command\-line\-tool/vi/vi\-tips|site/command\-line\-tool/git/git\-tips|site/en/aws|site/en/raspberrypi|site/en/markdown|site/en/application|site/en/command\-line\-tool|site/en/database|site/en/programming\-language|site/en/aws/aws_cli\-tips|site/en/aws/dynamodb|site/en/aws/dynamodb/dynamodb\-local|site/en/raspberrypi/raspberrypi\-ubuntu\-tips|site/en/markdown/markdown\-tips|site/en/application/shortcuts|site/en/application/vscode|site/en/application/obsidian|site/en/application/workflowy|site/en/application/inkscape|site/en/application/vscode/images|site/en/application/vscode/setting\-tips|site/en/application/vscode/extention\-tips|site/en/application/obsidian/community_plugins|site/en/application/obsidian/images|site/en/application/obsidian/community_plugins/auto_template_trigger|site/en/application/obsidian/community_plugins/plantuml|site/en/application/inkscape/images|site/en/command\-line\-tool/vi|site/en/command\-line\-tool/git|site/en/command\-line\-tool/vi/vi\-tips|site/en/command\-line\-tool/git/git\-tips|site/en/database/mariadb|site/en/database/mongodb|site/en/database/dynamodb|site/en/database/mongodb/images|site/en/database/mongodb/pymongo|site/en/database/mongodb/mongosh|site/en/database/mongodb/install\-mongodb|site/en/database/mongodb/mongodb\-compass|site/en/programming\-language/applescript|site/en/programming\-language/python|site/en/programming\-language/applescript/example|site/en/programming\-language/python/images|site/en/programming\-language/python/pre\-commit\-tips|site/en/programming\-language/python/pymysql\-tips|site/en/programming\-language/python/mdformat\-tips|site/en/programming\-language/python/mkdocs|site/en/programming\-language/python/mkdocs\-tips|site/en/programming\-language/python/post\-commit\-tips|site/en/programming\-language/python/dash\-plotly\-tips|site/en/programming\-language/python/mkdocs/doc_config\-tips|site/en/programming\-language/python/mkdocs/display\-config_tips|site/database/mariadb|site/database/mongodb|site/database/dynamodb|site/database/mongodb/images|site/database/mongodb/pymongo|site/database/mongodb/mongosh|site/database/mongodb/install\-mongodb|site/database/mongodb/mongodb\-compass|site/programming\-language/applescript|site/programming\-language/python|site/programming\-language/applescript/example|site/programming\-language/python/images|site/programming\-language/python/pre\-commit\-tips|site/programming\-language/python/pymysql\-tips|site/programming\-language/python/mdformat\-tips|site/programming\-language/python/mkdocs|site/programming\-language/python/post\-commit\-tips|site/programming\-language/python/dash\-plotly\-tips|site/programming\-language/python/mkdocs/doc_config\-tips|site/programming\-language/python/mkdocs/display\-config_tips|site/assets/images|site/assets/img|site/assets/stylesheets|site/assets/javascripts|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min)/.*'
      - id: mixed-line-ending
        args: [--fix=lf]
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml
        # Exclude check for "could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:materialx.emoji.twemoji'"
        args: [--unsafe]

  # https://python-poetry.org/docs/pre-commit-hooks/#usage
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        verbose: true
      - id: poetry-lock
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        verbose: true
        files: ^pyproject\.toml$
      - id: poetry-export
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements-dev.txt",
          "--without-hashes"]
        verbose: true
        files: ^pyproject\.toml$

  # https://github.com/shellcheck-py/shellcheck-py?tab=readme-ov-file#usage
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.5
    hooks:
      - id: actionlint

  #- repo: https://github.com/executablebooks/mdformat
  #  rev: 0.7.17
  #  hooks:
  #    - id: mdformat
  #      args: ["--check"]
  #      additional_dependencies:
  #        - mdformat-admon
  #        - mdformat-footnote
  #        - mdformat-frontmatter

  # Reference: https://github.com/DavidAnson/markdownlint-cli2#overview
  # > markdownlint-cli is a traditional command-line interface for markdownlint.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.jsonc", "README.md", "docs/**/*.md"]

  # Reference: https://github.com/DavidAnson/markdownlint-cli2#overview
  # > markdownlint-cli2はmarkdownlint用の少し型破りなコマンドラインインターフェイスです。
  # > markdownlint-cli2は設定ベースで、速度とシンプルさを優先しています。
  # > markdownlint-cli2はmarkdownlint-cliのすべての機能をサポートしています（少し異なる場合もあります）。
  #- repo: https://github.com/DavidAnson/markdownlint-cli2
  #  rev: v0.10.0
  #  hooks:
  #    - id: markdownlint-cli2
  #      args:
  #        [
  #          "--fix",
  #          "--config",
  #          ".markdownlint.jsonc",
  #          "README.md",
  #          "docs/**/*.md",
  #        ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: ["--fix", "ci"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20240622]
        args: [--config-file=pyproject.toml]
