# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Specify version or tag to use (as of 23.5.31)
    rev: v4.4.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '(site|site/sample|site/database|site/command\-line\-tool|site/assets|site/en|site/programming\-language|site/markdown|site/raspberrypi|site/search|site/application|site/sample/sample\-tips|site/database/mariadb\-tips|site/command\-line\-tool/vi|site/command\-line\-tool/git|site/command\-line\-tool/vi/vi\-tips|site/command\-line\-tool/git/git\-tips|site/assets/javascripts|site/assets/images|site/assets/stylesheets|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min|site/en/sample|site/en/database|site/en/command\-line\-tool|site/en/programming\-language|site/en/markdown|site/en/raspberrypi|site/en/application|site/en/sample/sample\-tips|site/en/database/mariadb\-tips|site/en/command\-line\-tool/vi|site/en/command\-line\-tool/git|site/en/command\-line\-tool/vi/vi\-tips|site/en/command\-line\-tool/git/git\-tips|site/en/programming\-language/applescript|site/en/programming\-language/python|site/en/programming\-language/applescript/example|site/en/programming\-language/python/post\-commit\-tips|site/en/programming\-language/python/mdformat\-tips|site/en/programming\-language/python/mkdocs\-tips|site/en/programming\-language/python/pymysql\-tips|site/en/programming\-language/python/dash\-plotly\-tips|site/en/programming\-language/python/pre\-commit\-tips|site/en/markdown/markdown\-tips|site/en/raspberrypi/raspberrypi\-ubuntu\-tips|site/en/application/vscode|site/en/application/workflowy|site/en/application/inkscape|site/en/application/obsidian|site/en/application/vscode/extention\-tips|site/en/application/vscode/setting\-tips|site/en/application/workflowy/workflowy\-tips|site/en/application/inkscape/inkscape\-tips|site/en/application/obsidian/obsidian\-tips|site/programming\-language/applescript|site/programming\-language/python|site/programming\-language/applescript/example|site/programming\-language/python/post\-commit\-tips|site/programming\-language/python/mdformat\-tips|site/programming\-language/python/mkdocs\-tips|site/programming\-language/python/pymysql\-tips|site/programming\-language/python/dash\-plotly\-tips|site/programming\-language/python/images|site/programming\-language/python/pre\-commit\-tips|site/markdown/markdown\-tips|site/raspberrypi/raspberrypi\-ubuntu\-tips|site/application/vscode|site/application/workflowy|site/application/inkscape|site/application/obsidian|site/application/vscode/extention\-tips|site/application/vscode/setting\-tips|site/application/workflowy/workflowy\-tips|site/application/inkscape/inkscape\-tips|site/application/inkscape/images|site/application/obsidian/obsidian\-tips)/.*'
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
        # Unify line break code to LF
        exclude: '(site|site/sample|site/database|site/command\-line\-tool|site/assets|site/en|site/programming\-language|site/markdown|site/raspberrypi|site/search|site/application|site/sample/sample\-tips|site/database/mariadb\-tips|site/command\-line\-tool/vi|site/command\-line\-tool/git|site/command\-line\-tool/vi/vi\-tips|site/command\-line\-tool/git/git\-tips|site/assets/javascripts|site/assets/images|site/assets/stylesheets|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min|site/en/sample|site/en/database|site/en/command\-line\-tool|site/en/programming\-language|site/en/markdown|site/en/raspberrypi|site/en/application|site/en/sample/sample\-tips|site/en/database/mariadb\-tips|site/en/command\-line\-tool/vi|site/en/command\-line\-tool/git|site/en/command\-line\-tool/vi/vi\-tips|site/en/command\-line\-tool/git/git\-tips|site/en/programming\-language/applescript|site/en/programming\-language/python|site/en/programming\-language/applescript/example|site/en/programming\-language/python/post\-commit\-tips|site/en/programming\-language/python/mdformat\-tips|site/en/programming\-language/python/mkdocs\-tips|site/en/programming\-language/python/pymysql\-tips|site/en/programming\-language/python/dash\-plotly\-tips|site/en/programming\-language/python/pre\-commit\-tips|site/en/markdown/markdown\-tips|site/en/raspberrypi/raspberrypi\-ubuntu\-tips|site/en/application/vscode|site/en/application/workflowy|site/en/application/inkscape|site/en/application/obsidian|site/en/application/vscode/extention\-tips|site/en/application/vscode/setting\-tips|site/en/application/workflowy/workflowy\-tips|site/en/application/inkscape/inkscape\-tips|site/en/application/obsidian/obsidian\-tips|site/programming\-language/applescript|site/programming\-language/python|site/programming\-language/applescript/example|site/programming\-language/python/post\-commit\-tips|site/programming\-language/python/mdformat\-tips|site/programming\-language/python/mkdocs\-tips|site/programming\-language/python/pymysql\-tips|site/programming\-language/python/dash\-plotly\-tips|site/programming\-language/python/images|site/programming\-language/python/pre\-commit\-tips|site/markdown/markdown\-tips|site/raspberrypi/raspberrypi\-ubuntu\-tips|site/application/vscode|site/application/workflowy|site/application/inkscape|site/application/obsidian|site/application/vscode/extention\-tips|site/application/vscode/setting\-tips|site/application/workflowy/workflowy\-tips|site/application/inkscape/inkscape\-tips|site/application/inkscape/images|site/application/obsidian/obsidian\-tips)/.*'
      - id: mixed-line-ending
        args: [--fix=lf]
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml

  # https://python-poetry.org/docs/pre-commit-hooks/#usage
  - repo: https://github.com/python-poetry/poetry
    # Cannot be executed with local designation (as of 23.5.31)
    rev: 1.6.1
    hooks:
      - id: poetry-check
        verbose: true
      - id: poetry-lock
        verbose: true
      - id: poetry-export
        args: [-f, requirements.txt, -o, requirements.txt]
        verbose: true
        files: ^pyproject\.toml$
      - id: poetry-export
        args: [--dev, -f, requirements.txt, -o, requirements-dev.txt]
        verbose: true
        files: ^pyproject\.toml$

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-admon
          - mdformat-footnote

  # Repository local hooks
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort ci scripts
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black ci scripts
        types: [python]
        exclude: resources_bin.py

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8 ci scripts
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]

      #- id: mdformat
      #  name: mdformat
      #  stages: [commit]
      #  language: system
      #  entry: poetry run mdformat .
      #  types: [markdown]

      # Original script
      - id: update-pyproject
        name: mkdocs build
        entry: poetry run python ci/run_mkdocs_cmd.py
        language: system
        verbose: true
        pass_filenames: false
        stages: [commit]
        additional_dependencies: []

      - id: update-pyproject
        name: Update pyproject.toml version
        entry: poetry run python ci/update_pyproject_version.py
        language: system
        verbose: true
        pass_filenames: false
        stages: [commit]
        additional_dependencies: []
