# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Specify version or tag to use (as of 23.5.31)
    rev: v4.4.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '(site|site/database|site/vi|site/tools|site/python|site/markdown|site/ja|site/search|site/sample|site/en|site/vscode|site/assets|site/git|site/raspberrypi|site/database/mariadb\-tips|site/vi/vi\-tips|site/tools/tools\-tips|site/python/post\-commit\-tips|site/python/images|site/python/pre\-commit\-tips|site/python/pymysql\-tips|site/python/dash\-plotly\-tips|site/python/mdformat\-tips|site/markdown/markdown\-tips|site/ja/database|site/ja/vi|site/ja/tools|site/ja/python|site/ja/markdown|site/ja/sample|site/ja/vscode|site/ja/git|site/ja/raspberrypi|site/ja/database/mariadb\-tips|site/ja/vi/vi\-tips|site/ja/tools/tools\-tips|site/ja/python/post\-commit\-tips|site/ja/python/images|site/ja/python/pre\-commit\-tips|site/ja/python/pymysql\-tips|site/ja/python/dash\-plotly\-tips|site/ja/python/mdformat\-tips|site/ja/markdown/markdown\-tips|site/ja/sample/sample\-tips|site/ja/vscode/vscode\-tips|site/ja/git/git\-tips|site/ja/raspberrypi/raspberrypi\-ubuntu\-tips|site/sample/sample\-tips|site/en/database|site/en/vi|site/en/tools|site/en/python|site/en/markdown|site/en/sample|site/en/vscode|site/en/git|site/en/raspberrypi|site/en/database/mariadb\-tips|site/en/vi/vi\-tips|site/en/tools/tools\-tips|site/en/python/post\-commit\-tips|site/en/python/images|site/en/python/pre\-commit\-tips|site/en/python/pymysql\-tips|site/en/python/dash\-plotly\-tips|site/en/python/mdformat\-tips|site/en/markdown/markdown\-tips|site/en/sample/sample\-tips|site/en/vscode/vscode\-tips|site/en/git/git\-tips|site/en/raspberrypi/raspberrypi\-ubuntu\-tips|site/vscode/vscode\-tips|site/assets/images|site/assets/javascripts|site/assets/stylesheets|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min|site/git/git\-tips|site/raspberrypi/raspberrypi\-ubuntu\-tips)/.*'
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
        # Unify line break code to LF
        exclude: '(site|site/database|site/vi|site/tools|site/python|site/markdown|site/ja|site/search|site/sample|site/en|site/vscode|site/assets|site/git|site/raspberrypi|site/database/mariadb\-tips|site/vi/vi\-tips|site/tools/tools\-tips|site/python/post\-commit\-tips|site/python/images|site/python/pre\-commit\-tips|site/python/pymysql\-tips|site/python/dash\-plotly\-tips|site/python/mdformat\-tips|site/markdown/markdown\-tips|site/ja/database|site/ja/vi|site/ja/tools|site/ja/python|site/ja/markdown|site/ja/sample|site/ja/vscode|site/ja/git|site/ja/raspberrypi|site/ja/database/mariadb\-tips|site/ja/vi/vi\-tips|site/ja/tools/tools\-tips|site/ja/python/post\-commit\-tips|site/ja/python/images|site/ja/python/pre\-commit\-tips|site/ja/python/pymysql\-tips|site/ja/python/dash\-plotly\-tips|site/ja/python/mdformat\-tips|site/ja/markdown/markdown\-tips|site/ja/sample/sample\-tips|site/ja/vscode/vscode\-tips|site/ja/git/git\-tips|site/ja/raspberrypi/raspberrypi\-ubuntu\-tips|site/sample/sample\-tips|site/en/database|site/en/vi|site/en/tools|site/en/python|site/en/markdown|site/en/sample|site/en/vscode|site/en/git|site/en/raspberrypi|site/en/database/mariadb\-tips|site/en/vi/vi\-tips|site/en/tools/tools\-tips|site/en/python/post\-commit\-tips|site/en/python/images|site/en/python/pre\-commit\-tips|site/en/python/pymysql\-tips|site/en/python/dash\-plotly\-tips|site/en/python/mdformat\-tips|site/en/markdown/markdown\-tips|site/en/sample/sample\-tips|site/en/vscode/vscode\-tips|site/en/git/git\-tips|site/en/raspberrypi/raspberrypi\-ubuntu\-tips|site/vscode/vscode\-tips|site/assets/images|site/assets/javascripts|site/assets/stylesheets|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min|site/git/git\-tips|site/raspberrypi/raspberrypi\-ubuntu\-tips)/.*'
      - id: mixed-line-ending
        args: [--fix=lf]
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml

  # https://python-poetry.org/docs/pre-commit-hooks/#usage
  - repo: https://github.com/python-poetry/poetry
    # Cannot be executed with local designation (as of 23.5.31)
    rev: 1.5.1
    hooks:
      - id: poetry-check
        verbose: true
      - id: poetry-lock
        verbose: true
      - id: poetry-export
        args: [-f, requirements.txt, -o, requirements.txt]
        verbose: true
        files: ^pyproject\.toml$
      - id: poetry-export
        args: [--dev, -f, requirements.txt, -o, requirements-dev.txt]
        verbose: true
        files: ^pyproject\.toml$

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-admon
          - mdformat-footnote

  # Repository local hooks
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort ci scripts
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black ci scripts
        types: [python]
        exclude: resources_bin.py

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8 ci scripts
        types: [python]

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]

      #- id: mdformat
      #  name: mdformat
      #  stages: [commit]
      #  language: system
      #  entry: poetry run mdformat .
      #  types: [markdown]

      # Original script
      - id: update-pyproject
        name: mkdocs build
        entry: poetry run python ci/run_mkdocs_cmd.py
        language: system
        verbose: true
        pass_filenames: false
        stages: [commit]
        additional_dependencies: []

      - id: update-pyproject
        name: Update pyproject.toml version
        entry: poetry run python ci/update_pyproject_version.py
        language: system
        verbose: true
        pass_filenames: false
        stages: [commit]
        additional_dependencies: []
