site_name: Dev Insights Tips
repo_name: 7rikazhexde/dev-insights-tips
repo_url: https://github.com/7rikazhexde/dev-insights-tips
copyright: "&copy; 2023 7rikazhexde"

theme:
  name: material
  custom_dir: overrides
  palette:
    # ライトモード
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        #name: ダークモードに切り替え
    # ダークモード
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        #name: ライトモードに切り替え
  font:
    text: Noto Sans
    code: Inconsolata
  language: ja
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.top
    #- navigation.expand
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/7rikazhexde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tw_7rikazhexde
    - icon: fontawesome/solid/blog
      link: https://7rikazhexde-techlog.hatenablog.com/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-4D30V35REY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thank you for your feedback!<br>
            Please use the comments(giscus) below to send us your feedback on this page.
          #note: >-
          #  Thanks for your feedback!<br>
          #  Please use the link below to provide feedback on this page.<br>
          #  <a href="https://github.com/7rikazhexde/dev-insights-tips/issues/new" target="_blank" rel="noopener">submit github new issue</a>
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thank you for your feedback!<br>
            Please use the comments(giscus) below to send me your feedback on this page or<br>
            use the link below to provide feedback on this page.<br>
            <a href="https://github.com/7rikazhexde/dev-insights-tips/issues/new" target="_blank" rel="noopener">submit github new issue</a>

nav:
  - Home:
      - index.md
  - Application:
      - application/index.ja.md
      - VSCode:
        - application/vscode/index.ja.md
        - application/vscode/setting-tips.ja.md
        - application/vscode/extention-tips.ja.md
      - Obsidian:
        - application/obsidian/obsidian-tips.ja.md
      - Workflowly:
        - application/workflowy/workflowy-tips.ja.md
      - Inkscape:
        - application/inkscape/inkscape-tips.ja.md
  - Command line tool:
      - command-line-tool/index.ja.md
      - vi:
        - command-line-tool/vi/vi-tips.ja.md
      - Git:
        - command-line-tool/git/git-tips.ja.md
  - Programming language:
      - programming-language/index.ja.md
      - Python:
        - programming-language/python/index.ja.md
        - programming-language/python/dash-plotly-tips.ja.md
        - programming-language/python/pre-commit-tips.ja.md
        - programming-language/python/post-commit-tips.ja.md
        - programming-language/python/pymysql-tips.ja.md
        - programming-language/python/mdformat-tips.ja.md
        - programming-language/python/mkdocs-tips.ja.md
      - AppleScript:
        - programming-language/applescript/index.ja.md
  - Database:
      - database/index.ja.md
      - database/mariadb-tips.ja.md
  - Markdown:
      - markdown/markdown-tips.ja.md
  - Raspberry Pi:
      - raspberrypi/index.ja.md
      - raspberrypi/raspberrypi-ubuntu-tips.ja.md

plugins:
  - search:
  - i18n:
      default_language: ja
      languages:
        en: English
        ja: 日本語
      nav_translations:
        en:
          #site_name: Dev Insights Tips
          Home: Home
          #Database: Database

markdown_extensions:
  - footnotes
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
